//
//  CreditsWebViewController.swift
//  pEp
//
//  Created by Andreas Buff on 05.10.20.
//  Copyright © 2020 p≡p Security S.A. All rights reserved.
//

import WebKit

class CreditsWebViewController: PEPWebViewController {

    // MARK: - Life Cycle

    override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 13.0, *) {
            webView.backgroundColor = UIColor.systemBackground
        } else {
            // Fallback on earlier versions
        }
        webView.loadHTMLString(html(), baseURL: nil)
        title = NSLocalizedString("Credits", comment: "Credits view title")
    }

    // MARK: - Private

    private func html() -> String {
        let appVersion = InfoPlist.versionDisplayString() ?? "666"
        var backgroundColor = UIColor.pEpLightBackground
        var fontColor = UIColor.pEpGray

        if #available(iOS 13.0, *) {
            backgroundColor = UIColor.systemBackground
            fontColor = UIColor.label
        } else {
            // Fallback on earlier versions
        }

        let fontSize = "18"
        let fontFamily = "Helvetica Neue"
        let fontWeight = "500"
        let styleP = "p {color: \(fontColor.toHexString());font-size: \(fontSize)px;font-family: \(fontFamily);font-weight: \(fontWeight);}"
        let styleBody = "body {background-color: \(backgroundColor.toHexString());}"
        let styleA = "a {color: \(fontColor.toHexString());font-size: \(fontSize)px;font-family: \(fontFamily);font-weight: \(fontWeight);}"
        let styleLink = "a:link {color:\(UIColor.pEpDarkGreenHex); text-decoration: underline; word-break: break-all; !important;}"
        let style = "<style>\(styleP)\(styleBody)\(styleA)\(styleLink)</style>"
        let result = """
        <html>
         <head>
           \(style)
           <meta name="viewport" content="width=device-width, initial-scale=1.0">
           <meta charset="utf-8"/>
        </head>
        <body>
        <blockquote>
        <p>&nbsp;</p>
        <p>p&equiv;p for iOS<br/> \(appVersion)</p>
        <p>&nbsp;</p>
        <p><a href="https://pep.security/docs">Documentation</a></p>
        <p><a href="mailto:support@pep.security">Support</a></p>
        <p>Thanks to:
        \(thanxRows())
        </p>

        <p>&nbsp;</p>
        <p>
        \(eula())
        </p>

        <p>&nbsp;</p>
        <p>
        \(licenseLumberjack())
        </p>

        </blockquote>
        </body>
        </html>
        """
        return result
    }

    private func thanxRows() -> String {
        let names = ["pEpEngine",
                     "Libassuan",
                     "Libksba",
                     "Libcurl",
                     "Libiconv",
                     "LibEtPan",
                     "Pantomime (GNUStep)",
                     "Pantomime (github)",
                     "OpenSSL-for-iPhone",
                     "SwipeCellKit",
                     "Lumberjack",
                     "AppAuth-iOS",
                     "Sequoia-PGP"]
        let links = ["https://gitea.pep.foundation/pEp.foundation/pEpEngine",
                     "https://gnupg.org/related_software/libassuan",
                     "https://gnupg.org/related_software/libksba",
                     "https://curl.haxx.se/libcurl/",
                     "https://www.gnu.org/software/libiconv/",
                     "https://www.etpan.org/libetpan.html",
                     "http://wiki.gnustep.org/index.php/Pantomime",
                     "https://github.com/timburks/Pantomime",
                     "https://github.com/x2on/OpenSSL-for-iPhone",
                     "https://github.com/SwipeCellKit/SwipeCellKit",
                     "https://github.com/CocoaLumberjack/CocoaLumberjack",
                     "https://github.com/openid/AppAuth-iOS",
                     "https://sequoia-pgp.org/"]

        var htmlThanx = ""
        for (i, name) in names.enumerated() {
            let link = links[i]
            let row = "<p><a href=\"\(link)\">\(name)</a></p>"
            htmlThanx += row
        }

        return "<div class=\"links\">\(htmlThanx)</div>"
    }

    private func eula() -> String {
        var backgroundColor = UIColor.pEpLightBackground
        var fontColor = UIColor.black
        if #available(iOS 13.0, *) {
            backgroundColor = UIColor.systemBackground
            fontColor = UIColor.label
        } else {
            // Fallback on earlier versions
        }

        let eula =
            """
            <p style="margin-bottom: 0.14in; line-height: 100%;" align="center"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>p&equiv;p APPLICATION END USER LICENSE AGREEMENT (EULA)</strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>1. General. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">The p&equiv;p Application is licensed, not sold, to You by pEp Security SA for use strictly in accordance with the terms and conditions of this License, and within any usage rules established by any deploying third party, which were agreed while deploying the p&equiv;p Application and are incorporated herein by this reference. The term "p&equiv;p Application" shall refer to and consist of the following: (i) the software application accompanying this License, including, without limitation, any software code, scripts, interfaces, graphics, displays, text, documentation and other components; (ii) any updates, modifications or enhancements to the items listed in subsection (i); and (iii) any specific website the p&equiv;p Application directs you to via any browser located on a Computer, Smartphone, Pad or such other device excluding Third Party Content. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>2. License Grant and Restrictions on Use. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>2.1 License Grant. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">pEp Security SA grants You a revocable, non-exclusive, non-transferable, limited right to install and use the p&equiv;p Application on a single Device owned and controlled by You, and to access and use the p&equiv;p Application on such Device strictly in accordance with the terms and conditions of this License, the Usage Rules and any service agreement associated with your Device (collectively "Related Agreements"). </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>2.2 Restrictions on Use. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You shall use the p&equiv;p Application strictly in accordance with the terms of the Related Agreements and shall not: (a) make any modification, adaptation, improvement, enhancement, translation or derivative work from the p&equiv;p Application; (b) violate any applicable laws, rules or regulations in connection with your access or use of the p&equiv;p Application; (c) remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of pEp Security SA or its affiliates, partners, suppliers or the licensors of the p&equiv;p Application; (d) use the p&equiv;p Application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended; (e) use the published source code of the p&equiv;p Application for any other purposes than rebuilding the p&equiv;p Application binary for comparing source code and binary code distributions on integrity; (f) install, use or permit the p&equiv;p Application to exist on more than one Device at a time or on any other device or computer; (g) distribute the p&equiv;p Application to multiple Devices; (h) make the p&equiv;p Application available over a network or other environment permitting access or use by multiple Devices or users at the same time; (i) use the p&equiv;p Application for creating a product, service or software that is, directly or indirectly, competitive with or in any way a substitute for any services, product or software offered by pEp Security SA or (j) use the p&equiv;p Application to send automated queries to any website or to send any unsolicited commercial e-mail. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>3. Intellectual Property Rights. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>3.1 Rights to p&equiv;p Application. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge and agree that the p&equiv;p Application and all copyrights, patents, trademarks, trade secrets and other intellectual property rights associated therewith are, and shall remain, the property of pEp Security SA. Furthermore, You acknowledge and agree that the source and object code of the Applications and the format, directories, queries, algorithms, structure and organization of the p&equiv;p Application are the intellectual property and proprietary and confidential information of pEp Security SA and its affiliates, licensors and suppliers. Except as expressly stated in this License, You are not granted any intellectual property rights in or to the p&equiv;p Application by implication, estoppel or other legal theory, and all rights in and to the p&equiv;p Application not expressly granted in this License are hereby reserved and retained by pEp Security SA. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>3.2 Third Party Software. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">The p&equiv;p Application may utilize or include third party software that is subject to Free Software and third party license terms ("Third Party Software"). You acknowledge and agree that Your right to use such Third Party Software as part of the p&equiv;p Application is subject to and governed by the terms and conditions of the Free Software or third party license applicable to such Third Party Software, including, without limitation, any applicable acknowledgements, license terms and disclaimers contained therein. In the event of a conflict between the terms of this License and the terms of such Free Software or third party licenses, the terms of the Free Software or third party licenses shall control with regard to Your use of the relevant Third Party Software.</span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>3.3 pEp Security SA&rsquo;s Marks. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You are not authorized to use the pEp Security SA trademarks in any advertising, publicity or in any other commercial manner without the prior written consent of pEp Security SA, which may be withheld for any or no reason. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>3.4 Infringement Acknowledgement. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You and pEp Security SA acknowledge and agree that, in the event of a third party claim that the p&equiv;p Application or Your possession or use of the p&equiv;p Application infringes any third party's intellectual property rights, You (and not pEp Security SA) will be responsible for the investigation, defense, settlement and discharge of any such claim of intellectual property infringement. You will, however, promptly notify pEp Security SA in writing of such a claim. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>4. Restriction on Transfer. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You may not rent, lease, lend, sublicense or transfer the p&equiv;p Application, this License or any of the rights granted hereunder. Any attempted transfer in contravention of this provision shall be null and void and of no force or effect. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>5. Use of Information. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>5.1 Consent to Use Information. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">pEp Security SA is a privacy project, and takes care that Your privacy will be respected. You agree, that pEp Security SA is storing and managing data about You, which is needed to fulfill the requirements of law and of all contracts, which You and pEp Security SA close. However, you may additionally grant pEp Security SA the right to collect statistical and usage data with the product You are using. In any such case, You are in control and can enable and disable data collection with easily reachable user interface. By enabling such functionality, you grant the right of usage of all collected data to pEp Security SA without restrictions; all such data then goes to the ownership of pEp Security SA. By disabling such functionality, you revoke this right for newly collected data, but not for formerly collected data where your acceptance was formerly given. Additionally to such data, You agree that there is technical, statistical and usage data collected and stored by the web system of pEp Security SA and the shop systems of pEp Security SA or third party, where products of pEp Security SA are described and deployed. For all data pEp Security SA has stored about You, pEp Security SA is intending not to violate privacy at all, and therefore never is profiling single people or storing any unneeded personal data. You have the right for receiving a copy of all personal data pEp Security SA is storing about You. Furthermore, you have the right to decide that pEp Security SA must delete all personal data about You, except such data, which pEp Security SA is legally bound to store (like invoice data for bookkeeping et.al.). pEp Security SA never sells personal data about you to third party, like address dealers.</span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>5.2 Privacy Policy. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">pEp Security SA is following a strict path of keeping Your privacy. There is no complicated Privacy Policy needed, because pEp Security SA only collects, manages and uses your data following the Consent to Use Information in 5.1.</span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6. Third Party Content and Services. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.1 General. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge that the p&equiv;p Application permits access to products, services, web-sites, advertisements, promotions, recommendations, advice, information, and materials created and provided by advertisers, publishers, content partners, marketing agents, vendors and other third parties ("Third Party Content and Services").</span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.2 Disclaimer. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge that pEp Security SA does not investigate, monitor, represent or endorse the Third Party Content and Services (including any third party websites available through the p&equiv;p Application). Furthermore, Your access to and use of the Third Party Content and Services is at Your sole discretion and risk, and pEp Security SA and its affiliates, partners, suppliers and licensors shall have no liability to You arising out of or in connection with Your access to and use of the Third Party Content and Services. pEp Security SA hereby disclaims any representation, warranty or guaranty regarding the Third Party Content and Services, whether express, implied or statutory, including, without limitation, the implied warranties of merchantability or fitness for a particular purpose, and any representation, warranty or guaranty regarding the availability, quality, reliability, features, appropriates, accuracy, completeness, or legality of the Third Party Content and Services. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.3 Third Party Terms of Service. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge and agree that Your access to and use of the Third Party Content and Services and any correspondence or business dealings between You and any third party located using the p&equiv;p Application are governed by and require Your acceptance of the terms of service of such third party, including, without limitation, any terms, privacy policies, conditions, representations, warranties or disclaimers contained therein. Furthermore, You acknowledge and agree that the Third Party Content and Services and any related third party terms of service are subject to change by the applicable third party at its sole discretion and without any notice. You assume all risks arising out of or resulting from your transaction of business over the Internet and with any third party, and you agree that pEp Security SA and its affiliates, partners, suppliers and licensors are not responsible or liable for any loss or result of the presence of information about or links to such advertisers or service providers. Furthermore, You acknowledge and agree that You are not being granted a license to (i) the Third Party Content and Services; (ii) any products, services, processes or technology described in or offered by the Third Party Content and Services; or (iii) any copyright, trademark, patent or other intellectual property right in the Third Party Content or Services or any products, services, processes or technology described or offered therein. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.4 Endorsements. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge and agree that the provision of access to any Third Party Content and Service shall not constitute or imply any endorsement by pEp Security SA or its affiliates of such Third Party Content and Services. pEp Security SA reserves the right to restrict or deny access to any Third Party Content and Services otherwise accessible through the p&equiv;p Application, although pEp Security SA has no obligation to restrict or deny access even if requested by You. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.5 Inappropriate Materials. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You understand that by accessing and using the Third Party Content and Services, You may encounter information, materials and subject matter (i) that You or others may deem offensive, indecent, or objectionable; (ii) which may or may not be identified as having explicit language, and (iii) that automatically and unintentionally appears in search results, as a link or reference to objectionable material. Notwithstanding the foregoing, You agree to use the Third Party Content and Services at Your sole risk and that pEp Security SA and its affiliates, partners, suppliers and licensors shall have no liability to You for information, material or subject matter that is found to be offensive, indecent, or objectionable. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>6.6 Use of Third Party Content and Services. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You agree that the Third Party Content and Services contain proprietary information and material, and are protected by applicable intellectual property and other laws, including, without limitation, pursuant to copyright. You agree that You will not use such proprietary information or materials in any way whatsoever except for permitted use of the Third Party Content and Services. No portion of the Third Party Content and Services may be reproduced in any form or by any means. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Third Party Content and Services, in any manner, and You shall not exploit the Third Party Content and Services in any unauthorized way whatsoever, including, without limitation, by trespass or burdening network capacity. You agree that You will not use any Third Party Content and Services in a manner that would infringe or violate the rights of any other party, and that pEp Security SA is not in any way responsible for any such use by You. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>7. Term and Termination. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>7.1 Term. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">This License shall be effective until terminated. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>7.2 Termination. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">If You fail to comply with any terms and conditions of this License, then this License and any rights afforded to You hereunder shall terminate automatically, without any notice or other action by pEp Security SA. Upon the termination of this License, You shall cease all use of the p&equiv;p Application and uninstall the p&equiv;p Application. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>8. Disclaimer of Warranties. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">YOU ACKNOWLEDGE AND AGREE THAT THE APPLICATION IS PROVIDED ON AN "AS IS' AND "AS AVAILABLE" BASIS, AND THAT YOUR USE OF OR RELIANCE UPON THE APPLICATION AND ANY THIRD PARTY CONTENT AND SERVICES ACCESSED THEREBY IS AT YOUR SOLE RISK AND DISCRETION. PEP SECURITY SA AND ITS AFFILIATES, PARTNERS, SUPPLIERS AND LICENSORS HEREBY DISCLAIM ANY AND ALL REPRSENTATIONS, WARRANTIES AND GUARANTIES REGARDING THE APPLICATION AND THIRD PARTY CONTENT AND SERVICES, WHETHER EXPRESS, IMPLIED OR STATUTORY, AND INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. FURTHERMORE, PEP SECURITY SA AND ITS AFFILIATES, PARTNERS, SUPPLIERS AND LICENSORS MAKE NO WARRANTY THAT (I) THE APPLICATION OR THIRD PARTY CONTENT AND SERVICES WILL MEET YOUR REQUIREMENTS; (II) THE APPLICATION OR THIRD PARTY CONTENT AND SERVICES WILL BE UNINTERRUPED, ACCURATE, RELIABLE, TIMELY, SECURE OR ERROR-FREE; (III) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL ACCESSED OR OBTAINED BY YOU THROUGH THE APPLICATION WILL BE AS REPRESENTED OR MEET YOUR EXPECTATIONS; OR (IV) ANY ERRORS IN THE APPLICATION OR THIRD PARTY CONENT AND SERVICES WILL BE CORRECTED. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM COMPANY OR FROM THE APPLICATION SHALL CREATE ANY REPRESENTATION, WARRANTY OR GUARANTY. FURTHERMORE, YOU ACKNOWLEDGE THAT PEP SECURITY SA HAS NO OBLIGATION TO CORRECT ANY ERRORS OR OTHERWISE SUPPORT OR MAINTAIN THE APPLICATION THAN OTHERWISE AGREED OUTSIDE THIS LICENSE.</span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>9. Limitation of Liability. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">UNDER NO CIRCUMSTANCES SHALL PEP SECURITY SA OR ITS AFFILIATES, PARTNERS, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS OR USE OF OR INABILITY TO ACCESS OR USE THE APPLICATION AND ANY THIRD PARTY CONTENT AND SERVICES, WHETHER OR NOT THE DAMAGES WERE FORESEEABLE AND WHETHER OR NOT PEP SECURITY SA WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, PEP SECURITY SA'S AGGREGATE LIABILITY TO YOU (WHETHER UNDER CONTRACT, TORT, STATUTE OR OTHERWISE) SHALL NOT EXCEED THE AMOUNT OF FIFTY DOLLARS ($50.00). THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>10. Indemnification. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You shall indemnify, defend and hold harmless pEp Security SA and its affiliates, partners, suppliers and licensors, and each of their respective officers, directors, agents and employees (the "Indemnified Parties") from and against any claim, proceeding, loss, damage, fine, penalty, interest and expense (including, without limitation, fees for attorneys and other professional advisors) arising out of or in connection with the following: (i) Your access to or use of the p&equiv;p Application or Third Party Content and Services; (ii) Your breach of this License; (iii) Your violation of law; (iv) Your negligence or willful misconduct; or (v) Your violation of the rights of a third party, including the infringement by You of any intellectual property or misappropriation of any proprietary right or trade secret of any person or entity. These obligations will survive any termination of the License. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>11. Compatibility. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">pEp Security SA does not warrant that the p&equiv;p Application will be compatible or interoperable with Your Device or any other piece of hardware, software, equipment or device installed on or used in connection with your Device. Furthermore, You acknowledge that compatibility and interoperability problems can cause the performance of your Device to diminish or fail completely, and may result in permanent the damage to Your Device, loss of the data located on Your Device, and corruption of the software and files located on Your Device. You acknowledge and agree that pEp Security SA and its affiliates, partners, suppliers and licensors shall have no liability to You for any losses suffered resulting from or arising in connection with compatibility or interoperability problems. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>12. Product Claims. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You acknowledge that You (not pEp Security SA) are responsible for addressing any third party claims relating to Your use or possession of the p&equiv;p Application, and agree to notify pEp Security SA of any third party claims relating to the p&equiv;p Application of which You become aware. Furthermore, You hereby release pEp Security SA from any liability resulting from Your use or possession of the p&equiv;p Application, including, without limitation, the following: (i) any product liability claims; (ii) any claim that the p&equiv;p Application fails to conform to any applicable legal or regulatory requirement; and (iii) any claim arising under consumer protection or similar legislation. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13. Miscellaneous. </strong></span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.1 Governing Law. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">This License shall be deemed to take place in the State of Luxembourg and shall be governed by and construed in accordance with the laws of the State of Luxembourg, excluding its conflicts of law principles. Any disputes arising from this License shall be adjudicated in the courts of the City of Luxembourg. This License shall not be governed by the United Nations Convention on Contracts for the International Sale of Goods, the application of which is expressly excluded. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.2 Severability. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">If any provision of this License is held to be invalid or unenforceable with respect to a party, the remainder of this License, or the application of such provision to persons other than those to whom it is held invalid or unenforceable shall not be affected and each remaining provision of this License shall be valid and enforceable to the fullest extent permitted by law. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.3 Waiver. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">Except as provided herein, the failure to exercise a right or require performance of an obligation under this License shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.4 Export Control. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">You may not use or otherwise export or re-export the p&equiv;p Application except as authorized by United States law and the laws of the jurisdiction(s) in which the p&equiv;p Application was obtained. You represent and warrant that You are not (x) located in any country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country, or (y) listed on any U.S. Government list of prohibited or restricted parties including the Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person's List or Entity List. You also agree that You will not use the p&equiv;p Application for any purposes prohibited by United States law. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.5 Modification or Amendment. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">pEp Security SA may modify or amend the terms of this License by posting a copy of the modified or amended License on the pEp Security SA p&equiv;p Application EULA website. You will be deemed to have agreed to any such modification or amendment by Your decision to continue using the p&equiv;p Application following the date in which the modified or amended License is posted on the pEp Security SA p&equiv;p Application EULA website. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.6 Survival. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">The following sections of this License and any other provisions of this License which by their express language or by their context are intended to survive the termination of this License shall survive such termination: 1, 2.2, 3, 4, 5, 7, 8, 9, 10, 12 and 13. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.7 Assignment. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">Except as permitted in Section 4, You shall not assign this License or any rights or obligations herein without the prior written consent of pEp Security SA and any attempted assignment in contravention of this provision shall be null and void and of no force or effect. </span></span></span></span></p>
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en"><strong>13.8 Entire Agreement. </strong></span></span></span></span><span style="color: \(fontColor.toHexString());"><span style="font-family: Times New Roman, serif;"><span style="font-size: x-large;"><span lang="en">This License including the documents incorporated herein by reference constitute the entire agreement with respect to the use of the p&equiv;p Application licensed hereunder and supersedes all prior or contemporaneous understandings regarding such subject matter</span></span></span></span></p>
            """
        return eula
    }

    private func licenseLumberjack() -> String {
        let license = p("BSD 3-Clause License") +
            p("Copyright (c) 2010-2020, Deusty, LLC<br>All rights reserved.") +
            p("Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:") +
            p("1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.") +
            p("2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.") +
            p("3. Neither the name of Deusty nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission of Deusty, LLC.") +
            p("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.")
        return license
    }

    private func p(_ text: String) -> String {
        var fontColor = UIColor.black
        if #available(iOS 13.0, *) {
            fontColor = UIColor.label
        } else {
            // Nothing to do
        }
        return """
            <p style="margin-bottom: 0.14in; line-height: 100%;"><span style="color: \(fontColor.toHexString()); font-family: Times New Roman, serif; font-size: x-large;" lang="en">
                \(text)
            </span></p>
        """
    }
}
